language: python
os: linux
dist: bionic

branches:
  only:
    - master
    - /\d+\.\d+.*/
  except:
    - gh-pages

install:
  - pip3 install -r requirements.txt
  - pip3 install .

before_script:
  - pip3 install -r tests/requirements.txt

script:
  - pytest --cov=expertsystem

jobs:
  include:
    - name: "Build and test documentation"
      python: 3.7
      before_script:
        - sudo apt-get -y install pandoc
        - pip3 install -r doc/requirements.txt
      script:
        - cd doc
        - make linkcheck
        - NBSPHINX_EXECUTE='' make html

    - name: "Style checks"
      python: 3.6
      script:
        - pip3 install -r requirements-dev.txt
        - black . --check
        - pre-commit run nbstripout -a
        - pre-commit run prettier -a
        - pre-commit run rstcheck -a

    - name: "Python 3.6 on Ubuntu 18.04"
      python: 3.6

    - name: "Python 3.7 on Ubuntu 18.04 + CodeCov"
      python: 3.7
      after_success:
        - pip3 install codecov
        - codecov

    - name: "Python 3.8 on Ubuntu 18.04"
      python: 3.8

    - name: "Python 3.7 on macOS (xcode11.2)"
      os: osx
      osx_image: xcode11.2
      language: shell

    - name: "Deploy PyPI package"
      install: echo "Skipping install stage"
      script: echo "Skipping script stage"
      before_script: echo "Skipping before_script stage"
      deploy:
        edge: true
        provider: pypi
        on:
          tags: true
        distributions: sdist
        skip_existing: false
        username: __token__
        password:
          secure: "Az4kKXl1wcsaV14CJg+fwc6bliPaPwimmCT7yYjWtmmPK8XOdla1IShnQmfKOEZkkmN4berUV/MQxDBbA8ckgCzNf/jp/I6nF4Jf7tFHh1JMsBWHs2noE5QqPF1F+Dt5oFltuGyRNQyOedCurZcDoiTe7KLcN+6JKYvR/VVDwDbHkosy7b39uDqO1tk9iJpUdtAtkFA1egVcZU1NLgiwFznPuTl3kEEWiGGV/80pFpXzUy5LmkAZe+REd13LS02UiplpKkCGFndooBO4JN6txbyvkapnEhmnCAYiY709/3BjidQ5vNPRPn+hu54xcxxFQ1BONhKOtbQnuUkKAJ3cFMCqimGgaqcPbrIx6ez/mVgazR5SsPZOSXoLOt/LfXwWNRwuxdWJO12sjS+dZbUjS+H+IWzbS6sbVXVP/s1Y4tq5I/ZUi4itgWxrrNh866HysbQNEulgm6wUTLhy6tJV3M+ydTKSJnssGElW9Cg3eLt3tIUIB2Nd/uizoBo56OxKqyVVA/LrKHgd8rnFx+914bx+PpRSv+JUFP3oEF5A+6ep/CAt1j8wONasgmlvpVqApnW4MRa2SflAP25qs4swHl/EJS/M/w65Ef9aAwwR8/9/F15aRFU8qNvEcxYJ7EHYvuQ7OJaOwp2rROhVemwBlxY/NKaTW27gKJFZ1B7uYUg="
