[Bug]
color = "d93f0b"
name = "Bug"
description = "Something isn't working"

[Epic]
color = "3E4B9E"
name = "Epic"
description = "Collection of issues, managed by ZenHub"

["âš ï¸ Interface"]
color = "BFDADC"
name = "âš ï¸ Interface"
description = "Changes to the interface"

["âšª Duplicate"]
color = "cfd3d7"
name = "âšª Duplicate"
description = "This issue or pull request already exists"

["âŒ Won't fix"]
color = "ffffff"
name = "âŒ Won't fix"
description = "This will not be worked on"

["â” Question"]
color = "88506B"
name = "â” Question"
description = "Discuss this matter in the team"

["ğŸ’¡ Feature"]
color = "c2e0c6"
name = "ğŸ’¡ Feature"
description = "New feature added to the package"

["ğŸ’« Good first issue"]
color = "F4EAEF"
name = "ğŸ’« Good first issue"
description = "Good for newcomers"

["ğŸ“ Docs"]
color = "bfd4f2"
name = "ğŸ“ Docs"
description = "Improvements or additions to documentation"

["ğŸ”¨ Maintenance"]
color = "FFCD8F"
name = "ğŸ”¨ Maintenance"
description = "Refactoring that doesn't affect the interface"

["ğŸ–±ï¸ DX"]
color = "fef2c0"
name = "ğŸ–±ï¸ DX"
description = "Improvements to the Developer Experience"
