name: Benchmark

env:
  FORCE_COLOR: "1"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - epic/*
  workflow_dispatch:

jobs:
  benchmark:
    name: Performance regression
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - uses: astral-sh/setup-uv@v7
      - name: Run pytest-benchmark
        run: uvx --from poethepoet poe benchmark
      - name: Warn on performance decrease
        if: github.event_name == 'pull_request'
        uses: benchmark-action/github-action-benchmark@v1
        with:
          benchmark-data-dir-path: ""
          comment-on-alert: true
          fail-on-alert: true
          gh-repository: github.com/ComPWA/ampform-benchmark-results
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name: AmpForm benchmark results
          output-file-path: benchmarks/output.json
          tool: pytest
      - name: Create local benchmark data repository
        if: github.event_name != 'pull_request'
        uses: benchmark-action/github-action-benchmark@v1
        with:
          benchmark-data-dir-path: ""
          gh-repository: github.com/ComPWA/ampform-benchmark-results
          github-token: ${{ secrets.PAT }}
          name: AmpForm benchmark results
          output-file-path: benchmarks/output.json
          tool: pytest
      - name: Push results to GitHub Pages
        if: github.event_name != 'pull_request'
        run: git push 'https://ComPWA:${{ secrets.PAT }}@github.com/ComPWA/ampform-benchmark-results' gh-pages
        working-directory: benchmark-data-repository
