name: Requirements (scheduled)

on:
  schedule:
    - cron: "0 2 */14 * *"
  workflow_dispatch:

jobs:
  pip-constraints:
    name: Update pip constraints files
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v2
      - uses: ComPWA/update-pip-constraints@main
        with:
          python-version: ${{ matrix.python-version }}

  pre-commit:
    name: pre-commit autoupdate
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ComPWA/update-pre-commit@main

  push:
    name: Create PR
    runs-on: ubuntu-20.04
    needs:
      - pip-constraints
      - pre-commit
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
        # GITHUB_TOKEN will not rerun checks after pushing to a PR branch
      - uses: actions/download-artifact@v2
      - run: ls -A
      - name: Move artifacts to correct location
        run: |
          if [[ -d artifact ]]; then
            cd artifact
            ls -A
            [[ -f .pre-commit-config.yaml ]] && mv -f .pre-commit-config.yaml ..
            [[ "$(ls)" != "" ]] && mv -f * ../.constraints/
          fi
      - run: git status -s
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "ci: update pip constraints and pre-commit config"
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          title: "ci: update pip constraints and pre-commit config"
          labels: |
            üñ±Ô∏è DX
          branch-suffix: timestamp
          delete-branch: true
          token: ${{ secrets.PAT }}
      - name: Print PR info
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
