name: Requirements (PR)

on:
  pull_request:
    branches:
      - main
      - epic/*

jobs:
  pip-constraints:
    name: Update pip constraints files
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if there are dependency changes
        run: git diff origin/main --exit-code -- .constraints setup.cfg
        continue-on-error: true
      - uses: ComPWA/update-pip-constraints@main
        if: success()
        with:
          python-version: ${{ matrix.python-version }}

  pre-commit:
    name: pre-commit autoupdate
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check if there are changes to pre-commit config
        run: git diff origin/main --exit-code -- .pre-commit-config.yml
        continue-on-error: true
      - uses: ComPWA/update-pre-commit@main
        if: success()

  push:
    name: Push changes
    if: github.event.pull_request.head.repo.full_name == github.repository
    # Only run if PR does not come from a fork
    # https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow
    runs-on: ubuntu-20.04
    needs:
      - pip-constraints
      - pre-commit
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
        # GITHUB_TOKEN will not rerun checks after pushing to a PR branch
      - uses: actions/download-artifact@v2
      - run: |
          [[ -f .pre-commit-config.yaml ]] && mv -f .pre-commit-config.yaml ..
          mv -f * ../.constraints/
        working-directory: artifact
      - run: git status -s
      - name: Commit and push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git config --global user.name "GitHub"
          git config --global user.email "noreply@github.com"
          git checkout -b ${GITHUB_HEAD_REF}
          if [[ $(git status -s) ]]; then
            git add -A
            git commit -m "ci: update pip constraints and pre-commit config"
            git config pull.rebase true
            git pull origin ${GITHUB_HEAD_REF}
            git push origin HEAD:${GITHUB_HEAD_REF}
          fi
