# cspell:ignore noreply

name: Requirements (PR)

on:
  pull_request:
    branches: [master]

jobs:
  upgrade:
    name: Upgrade requirement files
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - run: git fetch origin
      - name: Check for modified dependencies
        id: git-diff
        run:
          echo "::set-output name=dependency-changes::$(git diff
          origin/$GITHUB_BASE_REF --name-only -- reqs setup.cfg)"
        # Also triggers on (unwanted) changes to requirements.txt files
      - name: Show dependency changes changes
        run:
          git diff origin/$GITHUB_BASE_REF -- reqs/requirements*.in setup.cfg
      - name: Abort if fork PR and dependency changes
        if:
          github.event.pull_request.head.repo.full_name != github.repository &&
          steps.git-diff.outputs.dependency-changes != ''
        run: |
          echo "::error::Cannot modify package dependencies through a PR from a fork"
          exit 1
      - name: Set up Python ${{ matrix.python-version }}
        if: steps.git-diff.outputs.dependency-changes != ''
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: steps.git-diff.outputs.dependency-changes != ''
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
      - name: Upgrade dependencies
        if: steps.git-diff.outputs.dependency-changes != ''
        run: bash reqs/upgrade.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.python-version }}
          path: reqs/${{ matrix.python-version }}

  push:
    name: Push changes
    runs-on: ubuntu-20.04
    needs:
      - upgrade
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/download-artifact@v2
        with:
          path: reqs
      - run: git status -s
      - name: Commit and push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git config --global user.name ${{ github.actor }}
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout -b ${GITHUB_HEAD_REF}
          FILES_TO_COMMIT="reqs/*/requirements*.txt"
          if [[ $(git diff -- ${FILES_TO_COMMIT}) ]]; then
            git add ${FILES_TO_COMMIT}
            git commit -m "ci: upgrade developer dependencies (automatic)"
            git config pull.rebase true
            git pull origin ${GITHUB_HEAD_REF}
            git push origin HEAD:${GITHUB_HEAD_REF}
          fi
