name: Requirements (scheduled)

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  upgrade-requirements:
    name: Upgrade pinned requirements
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
      - name: Upgrade pinned requirements
        run: python3 .constraints/pin_requirements.py
      - uses: actions/upload-artifact@v2
        with:
          path: .constraints/py${{ matrix.python-version }}.txt

  upgrade-pre-commit:
    name: Upgrade pre-commit hooks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade pre-commit
      - name: Autoupdate pre-commit
        run: pre-commit autoupdate
      - uses: actions/upload-artifact@v2
        with:
          path: .pre-commit-config.yaml

  push:
    name: Create PR
    runs-on: ubuntu-20.04
    needs:
      - upgrade-pre-commit
      - upgrade-requirements
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/download-artifact@v2
        with:
          path: .constraints
      - run: |
          mv -f artifact/.pre-commit-config.yaml ..
          mv -f artifact/* .
        working-directory: .constraints
      - run: git status -s
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "ci: upgrade pinned requirements"
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          title: "ci: upgrade pinned requirements"
          labels: |
            üñ±Ô∏è DX
          branch-suffix: timestamp
          delete-branch: true
          token: ${{ secrets.PAT }}
      - name: Print PR info
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
