# cspell:ignore autoupdate noreply

name: Requirements (scheduled)

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch:

jobs:
  upgrade-reqs:
    name: Upgrade requirement files
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools
      - name: Upgrade dependencies
        run: bash reqs/upgrade.sh
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.python-version }}
          path: reqs/${{ matrix.python-version }}

  upgrade-pre-commit:
    name: Upgrade pre-commit hooks
    needs:
      - upgrade-reqs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r reqs/3.7/requirements-sty.txt
      - name: Perform style checks
        run: pre-commit autoupdate
      - uses: actions/upload-artifact@v2
        with:
          name: pre-commit
          path: .pre-commit-config.yaml

  push:
    name: Create PR
    runs-on: ubuntu-20.04
    needs:
      - upgrade-pre-commit
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - uses: actions/download-artifact@v2
        with:
          path: reqs
      - run: mv -f reqs/pre-commit/.pre-commit-config.yaml .
      - run: git status -s
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "ci: upgrade developer dependencies"
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          title: "ci: upgrade developer dependencies"
          labels: |
            üñ±Ô∏è DX
          branch-suffix: timestamp
          delete-branch: true
          token: ${{ secrets.PAT }}
      - name: Print PR info
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
